export default [
  {
    name: 'The Fool',
    arcana: 'major',
    number: 0,
    suit: null,
    court: null,
    image: 'major-00-the-fool.jpg',
  },
  {
    name: 'The Magician',
    arcana: 'major',
    number: 1,
    suit: null,
    court: null,
    image: 'major-01-the-magician.jpg',
  },
  {
    name: 'The High Priestess',
    arcana: 'major',
    number: 2,
    suit: null,
    court: null,
    image: 'major-02-the-high-priestess.jpg',
  },
  {
    name: 'The Empress',
    arcana: 'major',
    number: 3,
    suit: null,
    court: null,
    image: 'major-03-the-empress.jpg',
  },
  {
    name: 'The Emperor',
    arcana: 'major',
    number: 4,
    suit: null,
    court: null,
    image: 'major-04-the-emperor.jpg',
  },
  {
    name: 'The Hierophant',
    arcana: 'major',
    number: 5,
    suit: null,
    court: null,
    image: 'major-05-the-hierophant.jpg',
  },
  {
    name: 'The Lovers',
    arcana: 'major',
    number: 6,
    suit: null,
    court: null,
    image: 'major-06-the-lovers.jpg',
  },
  {
    name: 'The Chariot',
    arcana: 'major',
    number: 7,
    suit: null,
    court: null,
    image: 'major-07-the-chariot.jpg',
  },
  {
    name: 'Strength',
    arcana: 'major',
    number: 8,
    suit: null,
    court: null,
    image: 'major-08-strength.jpg',
  },
  {
    name: 'The Hermit',
    arcana: 'major',
    number: 9,
    suit: null,
    court: null,
    image: 'major-09-the-hermit.jpg',
  },
  {
    name: 'Wheel of Fortune',
    arcana: 'major',
    number: 10,
    suit: null,
    court: null,
    image: 'major-10-the-wheel-of-fortune.jpg',
  },
  {
    name: 'Justice',
    arcana: 'major',
    number: 11,
    suit: null,
    court: null,
    image: 'major-11-justice.jpg',
  },
  {
    name: 'The Hanged Man',
    arcana: 'major',
    number: 12,
    suit: null,
    court: null,
    image: 'major-12-the-hanged-man.jpg',
  },
  {
    name: 'Death',
    arcana: 'major',
    number: 13,
    suit: null,
    court: null,
    image: 'major-13-death.jpg',
  },
  {
    name: 'Temperance',
    arcana: 'major',
    number: 14,
    suit: null,
    court: null,
    image: 'major-14-temperance.jpg',
  },
  {
    name: 'The Devil',
    arcana: 'major',
    number: 15,
    suit: null,
    court: null,
    image: 'major-15-the-devil.jpg',
  },
  {
    name: 'The Tower',
    arcana: 'major',
    number: 16,
    suit: null,
    court: null,
    image: 'major-16-the-tower.jpg',
  },
  {
    name: 'The Star',
    arcana: 'major',
    number: 17,
    suit: null,
    court: null,
    image: 'major-17-the-star.jpg',
  },
  {
    name: 'The Moon',
    arcana: 'major',
    number: 18,
    suit: null,
    court: null,
    image: 'major-18-the-moon.jpg',
  },
  {
    name: 'The Sun',
    arcana: 'major',
    number: 19,
    suit: null,
    court: null,
    image: 'major-19-the-sun.jpg',
  },
  {
    name: 'Judgement',
    arcana: 'major',
    number: 20,
    suit: null,
    court: null,
    image: 'major-20-judgement.jpg',
  },
  {
    name: 'The World',
    arcana: 'major',
    number: 21,
    suit: null,
    court: null,
    image: 'major-21-the-world.jpg',
  },
  {
    name: 'Ace of Cups',
    arcana: 'minor',
    number: 1,
    suit: 'cup',
    court: null,
    image: 'cups-01.jpg',
  },
  {
    name: 'Two of Cups',
    arcana: 'minor',
    number: 2,
    suit: 'cup',
    court: null,
    image: 'cups-02.jpg',
  },
  {
    name: 'Three of Cups',
    arcana: 'minor',
    number: 3,
    suit: 'cup',
    court: null,
    image: 'cups-03.jpg',
  },
  {
    name: 'Four of Cups',
    arcana: 'minor',
    number: 4,
    suit: 'cup',
    court: null,
    image: 'cups-04.jpg',
  },
  {
    name: 'Five of Cups',
    arcana: 'minor',
    number: 5,
    suit: 'cup',
    court: null,
    image: 'cups-05.jpg',
  },
  {
    name: 'Six of Cups',
    arcana: 'minor',
    number: 6,
    suit: 'cup',
    court: null,
    image: 'cups-06.jpg',
  },
  {
    name: 'Seven of Cups',
    arcana: 'minor',
    number: 7,
    suit: 'cup',
    court: null,
    image: 'cups-07.jpg',
  },
  {
    name: 'Eight of Cups',
    arcana: 'minor',
    number: 8,
    suit: 'cup',
    court: null,
    image: 'cups-08.jpg',
  },
  {
    name: 'Nine of Cups',
    arcana: 'minor',
    number: 9,
    suit: 'cup',
    court: null,
    image: 'cups-09.jpg',
  },
  {
    name: 'Ten of Cups',
    arcana: 'minor',
    number: 10,
    suit: 'cup',
    court: null,
    image: 'cups-10.jpg',
  },
  {
    name: 'Page of Cups',
    arcana: 'minor',
    number: null,
    suit: 'cup',
    court: 'page',
    image: 'cups-11.jpg',
  },
  {
    name: 'Knight of Cups',
    arcana: 'minor',
    number: null,
    suit: 'cup',
    court: 'knight',
    image: 'cups-12.jpg',
  },
  {
    name: 'Queen of Cups',
    arcana: 'minor',
    number: null,
    suit: 'cup',
    court: 'queen',
    image: 'cups-13.jpg',
  },
  {
    name: 'King of Cups',
    arcana: 'minor',
    number: null,
    suit: 'cup',
    court: 'king',
    image: 'cups-14.jpg',
  },
  {
    name: 'Ace of Pentacles',
    arcana: 'minor',
    number: 1,
    suit: 'pentacle',
    court: null,
    image: 'pents-01.jpg',
  },
  {
    name: 'Two of Pentacles',
    arcana: 'minor',
    number: 2,
    suit: 'pentacle',
    court: null,
    image: 'pents-02.jpg',
  },
  {
    name: 'Three of Pentacles',
    arcana: 'minor',
    number: 3,
    suit: 'pentacle',
    court: null,
    image: 'pents-03.jpg',
  },
  {
    name: 'Four of Pentacles',
    arcana: 'minor',
    number: 4,
    suit: 'pentacle',
    court: null,
    image: 'pents-04.jpg',
  },
  {
    name: 'Five of Pentacles',
    arcana: 'minor',
    number: 5,
    suit: 'pentacle',
    court: null,
    image: 'pents-05.jpg',
  },
  {
    name: 'Six of Pentacles',
    arcana: 'minor',
    number: 6,
    suit: 'pentacle',
    court: null,
    image: 'pents-06.jpg',
  },
  {
    name: 'Seven of Pentacles',
    arcana: 'minor',
    number: 7,
    suit: 'pentacle',
    court: null,
    image: 'pents-07.jpg',
  },
  {
    name: 'Eight of Pentacles',
    arcana: 'minor',
    number: 8,
    suit: 'pentacle',
    court: null,
    image: 'pents-08.jpg',
  },
  {
    name: 'Nine of Pentacles',
    arcana: 'minor',
    number: 9,
    suit: 'pentacle',
    court: null,
    image: 'pents-09.jpg',
  },
  {
    name: 'Ten of Pentacles',
    arcana: 'minor',
    number: 10,
    suit: 'pentacle',
    court: null,
    image: 'pents-10.jpg',
  },
  {
    name: 'Page of Pentacles',
    arcana: 'minor',
    number: null,
    suit: 'pentacle',
    court: 'page',
    image: 'pents-11.jpg',
  },
  {
    name: 'Knight of Pentacles',
    arcana: 'minor',
    number: null,
    suit: 'pentacle',
    court: 'knight',
    image: 'pents-12.jpg',
  },
  {
    name: 'Queen of Pentacles',
    arcana: 'minor',
    number: null,
    suit: 'pentacle',
    court: 'queen',
    image: 'pents-13.jpg',
  },
  {
    name: 'King of Pentacles',
    arcana: 'minor',
    number: null,
    suit: 'pentacle',
    court: 'king',
    image: 'pents-14.jpg',
  },
  {
    name: 'Ace of Swords',
    arcana: 'minor',
    number: 1,
    suit: 'sword',
    court: null,
    image: 'swords-01.jpg',
  },
  {
    name: 'Two of Swords',
    arcana: 'minor',
    number: 2,
    suit: 'sword',
    court: null,
    image: 'swords-02.jpg',
  },
  {
    name: 'Three of Swords',
    arcana: 'minor',
    number: 3,
    suit: 'sword',
    court: null,
    image: 'swords-03.jpg',
  },
  {
    name: 'Four of Swords',
    arcana: 'minor',
    number: 4,
    suit: 'sword',
    court: null,
    image: 'swords-04.jpg',
  },
  {
    name: 'Five of Swords',
    arcana: 'minor',
    number: 5,
    suit: 'sword',
    court: null,
    image: 'swords-05.jpg',
  },
  {
    name: 'Six of Swords',
    arcana: 'minor',
    number: 6,
    suit: 'sword',
    court: null,
    image: 'swords-06.jpg',
  },
  {
    name: 'Seven of Swords',
    arcana: 'minor',
    number: 7,
    suit: 'sword',
    court: null,
    image: 'swords-07.jpg',
  },
  {
    name: 'Eight of Swords',
    arcana: 'minor',
    number: 8,
    suit: 'sword',
    court: null,
    image: 'swords-08.jpg',
  },
  {
    name: 'Nine of Swords',
    arcana: 'minor',
    number: 9,
    suit: 'sword',
    court: null,
    image: 'swords-09.jpg',
  },
  {
    name: 'Ten of Swords',
    arcana: 'minor',
    number: 10,
    suit: 'sword',
    court: null,
    image: 'swords-10.jpg',
  },
  {
    name: 'Page of Swords',
    arcana: 'minor',
    number: null,
    suit: 'sword',
    court: 'page',
    image: 'swords-11.jpg',
  },
  {
    name: 'Knight of Swords',
    arcana: 'minor',
    number: null,
    suit: 'sword',
    court: 'knight',
    image: 'swords-12.jpg',
  },
  {
    name: 'Queen of Swords',
    arcana: 'minor',
    number: null,
    suit: 'sword',
    court: 'queen',
    image: 'swords-13.jpg',
  },
  {
    name: 'King of Swords',
    arcana: 'minor',
    number: null,
    suit: 'sword',
    court: 'king',
    image: 'swords-14.jpg',
  },
  {
    name: 'Ace of Wands',
    arcana: 'minor',
    number: 1,
    suit: 'wand',
    court: null,
    image: 'wands-01.jpg',
  },
  {
    name: 'Two of Wands',
    arcana: 'minor',
    number: 2,
    suit: 'wand',
    court: null,
    image: 'wands-02.jpg',
  },
  {
    name: 'Three of Wands',
    arcana: 'minor',
    number: 3,
    suit: 'wand',
    court: null,
    image: 'wands-03.jpg',
  },
  {
    name: 'Four of Wands',
    arcana: 'minor',
    number: 4,
    suit: 'wand',
    court: null,
    image: 'wands-04.jpg',
  },
  {
    name: 'Five of Wands',
    arcana: 'minor',
    number: 5,
    suit: 'wand',
    court: null,
    image: 'wands-05.jpg',
  },
  {
    name: 'Six of Wands',
    arcana: 'minor',
    number: 6,
    suit: 'wand',
    court: null,
    image: 'wands-06.jpg',
  },
  {
    name: 'Seven of Wands',
    arcana: 'minor',
    number: 7,
    suit: 'wand',
    court: null,
    image: 'wands-07.jpg',
  },
  {
    name: 'Eight of Wands',
    arcana: 'minor',
    number: 8,
    suit: 'wand',
    court: null,
    image: 'wands-08.jpg',
  },
  {
    name: 'Nine of Wands',
    arcana: 'minor',
    number: 9,
    suit: 'wand',
    court: null,
    image: 'wands-09.jpg',
  },
  {
    name: 'Ten of Wands',
    arcana: 'minor',
    number: 10,
    suit: 'wand',
    court: null,
    image: 'wands-10.jpg',
  },
  {
    name: 'Page of Wands',
    arcana: 'minor',
    number: null,
    suit: 'wand',
    court: 'page',
    image: 'wands-11.jpg',
  },
  {
    name: 'Knight of Wands',
    arcana: 'minor',
    number: null,
    suit: 'wand',
    court: 'knight',
    image: 'wands-12.jpg',
  },
  {
    name: 'Queen of Wands',
    arcana: 'minor',
    number: null,
    suit: 'wand',
    court: 'queen',
    image: 'wands-13.jpg',
  },
  {
    name: 'King of Wands',
    arcana: 'minor',
    number: null,
    suit: 'wand',
    court: 'king',
    image: 'wands-14.jpg',
  },
];
