export default [
  {
    name: 'The Fool',
    arcana: 'major',
    number: 0,
    suit: null,
    court: null,
  },
  {
    name: 'The Magician',
    arcana: 'major',
    number: 1,
    suit: null,
    court: null,
  },
  {
    name: 'The High Priestess',
    arcana: 'major',
    number: 2,
    suit: null,
    court: null,
  },
  {
    name: 'The Empress',
    arcana: 'major',
    number: 3,
    suit: null,
    court: null,
  },
  {
    name: 'The Emperor',
    arcana: 'major',
    number: 4,
    suit: null,
    court: null,
  },
  {
    name: 'The Hierophant',
    arcana: 'major',
    number: 5,
    suit: null,
    court: null,
  },
  {
    name: 'The Lovers',
    arcana: 'major',
    number: 6,
    suit: null,
    court: null,
  },
  {
    name: 'The Chariot',
    arcana: 'major',
    number: 7,
    suit: null,
    court: null,
  },
  {
    name: 'Strength',
    arcana: 'major',
    number: 8,
    suit: null,
    court: null,
  },
  {
    name: 'The Hermit',
    arcana: 'major',
    number: 9,
    suit: null,
    court: null,
  },
  {
    name: 'Wheel of Fortune',
    arcana: 'major',
    number: 10,
    suit: null,
    court: null,
  },
  {
    name: 'Justice',
    arcana: 'major',
    number: 11,
    suit: null,
    court: null,
  },
  {
    name: 'The Hanged Man',
    arcana: 'major',
    number: 12,
    suit: null,
    court: null,
  },
  {
    name: 'Death',
    arcana: 'major',
    number: 13,
    suit: null,
    court: null,
  },
  {
    name: 'Temperance',
    arcana: 'major',
    number: 14,
    suit: null,
    court: null,
  },
  {
    name: 'The Devil',
    arcana: 'major',
    number: 15,
    suit: null,
    court: null,
  },
  {
    name: 'The Tower',
    arcana: 'major',
    number: 16,
    suit: null,
    court: null,
  },
  {
    name: 'The Star',
    arcana: 'major',
    number: 17,
    suit: null,
    court: null,
  },
  {
    name: 'The Moon',
    arcana: 'major',
    number: 18,
    suit: null,
    court: null,
  },
  {
    name: 'The Sun',
    arcana: 'major',
    number: 19,
    suit: null,
    court: null,
  },
  {
    name: 'Judgement',
    arcana: 'major',
    number: 20,
    suit: null,
    court: null,
  },
  {
    name: 'The World',
    arcana: 'major',
    number: 21,
    suit: null,
    court: null,
  },

  // Minor Arcana =================================

  { name: 'Ace of Cups', arcana: 'minor', number: 1, suit: 'cup', court: null },
  { name: 'Two of Cups', arcana: 'minor', number: 2, suit: 'cup', court: null },
  {
    name: 'Three of Cups',
    arcana: 'minor',
    number: 3,
    suit: 'cup',
    court: null,
  },
  {
    name: 'Four of Cups',
    arcana: 'minor',
    number: 4,
    suit: 'cup',
    court: null,
  },
  {
    name: 'Five of Cups',
    arcana: 'minor',
    number: 5,
    suit: 'cup',
    court: null,
  },
  { name: 'Six of Cups', arcana: 'minor', number: 6, suit: 'cup', court: null },
  {
    name: 'Seven of Cups',
    arcana: 'minor',
    number: 7,
    suit: 'cup',
    court: null,
  },
  {
    name: 'Eight of Cups',
    arcana: 'minor',
    number: 8,
    suit: 'cup',
    court: null,
  },
  {
    name: 'Nine of Cups',
    arcana: 'minor',
    number: 9,
    suit: 'cup',
    court: null,
  },
  {
    name: 'Ten of Cups',
    arcana: 'minor',
    number: 10,
    suit: 'cup',
    court: null,
  },
  {
    name: 'Page of Cups',
    arcana: 'minor',
    number: null,
    suit: 'cup',
    court: 'page',
  },
  {
    name: 'Knight of Cups',
    arcana: 'minor',
    number: null,
    suit: 'cup',
    court: 'knight',
  },
  {
    name: 'Queen of Cups',
    arcana: 'minor',
    number: null,
    suit: 'cup',
    court: 'queen',
  },
  {
    name: 'King of Cups',
    arcana: 'minor',
    number: null,
    suit: 'cup',
    court: 'king',
  },

  {
    name: 'Ace of Pentacles',
    arcana: 'minor',
    number: 1,
    suit: 'pentacle',
    court: null,
  },
  {
    name: 'Two of Pentacles',
    arcana: 'minor',
    number: 2,
    suit: 'pentacle',
    court: null,
  },
  {
    name: 'Three of Pentacles',
    arcana: 'minor',
    number: 3,
    suit: 'pentacle',
    court: null,
  },
  {
    name: 'Four of Pentacles',
    arcana: 'minor',
    number: 4,
    suit: 'pentacle',
    court: null,
  },
  {
    name: 'Five of Pentacles',
    arcana: 'minor',
    number: 5,
    suit: 'pentacle',
    court: null,
  },
  {
    name: 'Six of Pentacles',
    arcana: 'minor',
    number: 6,
    suit: 'pentacle',
    court: null,
  },
  {
    name: 'Seven of Pentacles',
    arcana: 'minor',
    number: 7,
    suit: 'pentacle',
    court: null,
  },
  {
    name: 'Eight of Pentacles',
    arcana: 'minor',
    number: 8,
    suit: 'pentacle',
    court: null,
  },
  {
    name: 'Nine of Pentacles',
    arcana: 'minor',
    number: 9,
    suit: 'pentacle',
    court: null,
  },
  {
    name: 'Ten of Pentacles',
    arcana: 'minor',
    number: 10,
    suit: 'pentacle',
    court: null,
  },
  {
    name: 'Page of Pentacles',
    arcana: 'minor',
    number: null,
    suit: 'pentacle',
    court: 'page',
  },
  {
    name: 'Knight of Pentacles',
    arcana: 'minor',
    number: null,
    suit: 'pentacle',
    court: 'knight',
  },
  {
    name: 'Queen of Pentacles',
    arcana: 'minor',
    number: null,
    suit: 'pentacle',
    court: 'queen',
  },
  {
    name: 'King of Pentacles',
    arcana: 'minor',
    number: null,
    suit: 'pentacle',
    court: 'king',
  },

  {
    name: 'Ace of Swords',
    arcana: 'minor',
    number: 1,
    suit: 'sword',
    court: null,
  },
  {
    name: 'Two of Swords',
    arcana: 'minor',
    number: 2,
    suit: 'sword',
    court: null,
  },
  {
    name: 'Three of Swords',
    arcana: 'minor',
    number: 3,
    suit: 'sword',
    court: null,
  },
  {
    name: 'Four of Swords',
    arcana: 'minor',
    number: 4,
    suit: 'sword',
    court: null,
  },
  {
    name: 'Five of Swords',
    arcana: 'minor',
    number: 5,
    suit: 'sword',
    court: null,
  },
  {
    name: 'Six of Swords',
    arcana: 'minor',
    number: 6,
    suit: 'sword',
    court: null,
  },
  {
    name: 'Seven of Swords',
    arcana: 'minor',
    number: 7,
    suit: 'sword',
    court: null,
  },
  {
    name: 'Eight of Swords',
    arcana: 'minor',
    number: 8,
    suit: 'sword',
    court: null,
  },
  {
    name: 'Nine of Swords',
    arcana: 'minor',
    number: 9,
    suit: 'sword',
    court: null,
  },
  {
    name: 'Ten of Swords',
    arcana: 'minor',
    number: 10,
    suit: 'sword',
    court: null,
  },
  {
    name: 'Page of Swords',
    arcana: 'minor',
    number: null,
    suit: 'sword',
    court: 'page',
  },
  {
    name: 'Knight of Swords',
    arcana: 'minor',
    number: null,
    suit: 'sword',
    court: 'knight',
  },
  {
    name: 'Queen of Swords',
    arcana: 'minor',
    number: null,
    suit: 'sword',
    court: 'queen',
  },
  {
    name: 'King of Swords',
    arcana: 'minor',
    number: null,
    suit: 'sword',
    court: 'king',
  },

  {
    name: 'Ace of Wands',
    arcana: 'minor',
    number: 1,
    suit: 'wand',
    court: null,
  },
  {
    name: 'Two of Wands',
    arcana: 'minor',
    number: 2,
    suit: 'wand',
    court: null,
  },
  {
    name: 'Three of Wands',
    arcana: 'minor',
    number: 3,
    suit: 'wand',
    court: null,
  },
  {
    name: 'Four of Wands',
    arcana: 'minor',
    number: 4,
    suit: 'wand',
    court: null,
  },
  {
    name: 'Five of Wands',
    arcana: 'minor',
    number: 5,
    suit: 'wand',
    court: null,
  },
  {
    name: 'Six of Wands',
    arcana: 'minor',
    number: 6,
    suit: 'wand',
    court: null,
  },
  {
    name: 'Seven of Wands',
    arcana: 'minor',
    number: 7,
    suit: 'wand',
    court: null,
  },
  {
    name: 'Eight of Wands',
    arcana: 'minor',
    number: 8,
    suit: 'wand',
    court: null,
  },
  {
    name: 'Nine of Wands',
    arcana: 'minor',
    number: 9,
    suit: 'wand',
    court: null,
  },
  {
    name: 'Ten of Wands',
    arcana: 'minor',
    number: 10,
    suit: 'wand',
    court: null,
  },
  {
    name: 'Page of Wands',
    arcana: 'minor',
    number: null,
    suit: 'wand',
    court: 'page',
  },
  {
    name: 'Knight of Wands',
    arcana: 'minor',
    number: null,
    suit: 'wand',
    court: 'knight',
  },
  {
    name: 'Queen of Wands',
    arcana: 'minor',
    number: null,
    suit: 'wand',
    court: 'queen',
  },
  {
    name: 'King of Wands',
    arcana: 'minor',
    number: null,
    suit: 'wand',
    court: 'king',
  },
];
